# These are supported funding model platforms
THONG-NGO_BitcoinCash
github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [quang7hong81.github.com, quang7hong81.github.io]
patreon: # Replace with a single Patreon username: quang7hong81 
open_collective: # Replace with a single Open Collective username: quangthong81  
ko_fi: # Replace with a single Ko-fi username: quangthong81 
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel: quangthong81  
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry: quangthong81 
liberapay: # Replace with a single Liberapay username: qusngthong81 
issuehunt: # Replace with a single IssueHunt username: quangthong81 
otechie: # Replace with a single Otechie username: quangthong81 
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['bch.info, 'bitcoincash.orrg', 'acceptbitcoin.cash', 'bitcoincashnode.org']
